services:
  nginx:
    depends_on:
      - mattermost
    container_name: nginx_mattermost
    networks:
      - texas-net
    image: docker.1ms.run/library/nginx
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /var/run
      - /var/cache
      - /var/log/nginx
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d:ro
      - ${NGINX_DHPARAMS_FILE}:/etc/nginx/dhparams4096.pem:ro
      - ${CERT_PATH}:/etc/nginx/certs/cert.pem:ro
      - ${KEY_PATH}:/etc/nginx/certs/key.pem:ro
      - shared-webroot:/usr/share/nginx/html:ro
      - /etc/nginx/ssl/blog.kawaro.space:/etc/nginx/ssl/blog.kawaro.space:ro
      - /opt/1panel/apps/halo/halo/live2d/live2d_api/model:/srv/live2d/model:ro
    environment:
      # timezone inside container
      - TZ
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
  mattermost:
    ports:
      - ${CALLS_PORT}:${CALLS_PORT}/udp
      - ${CALLS_PORT}:${CALLS_PORT}/tcp

# Shared volume for Let's Encrypt certificate renewal with a webroot
volumes:
  shared-webroot:
    name: shared-webroot

# This network name is being used for Let's Encrypt certificate renewal
networks:
  texas-net:
    external: true
    name: texas-net
