version: "3.9"

services:
  # PostgreSQL 数据库
  db:
    image: postgres:15
    container_name: texas-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - texas-net

  # Redis Broker
  redis:
    image: redis:7
    container_name: texas-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - texas-net

  # FastAPI + WebSocket 客户端服务
  bot:
    build:
      context: .
      dockerfile: infra/docker/bot.Dockerfile
    container_name: texas-bot
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db
      - redis
    networks:
      - texas-net

  # Celery Worker
  worker:
    build:
      context: .
      dockerfile: infra/docker/celery.Dockerfile
    container_name: texas-worker
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app/tasks
    command: ["celery", "-A", "celery_app", "worker", "--loglevel=info"]
    depends_on:
      - db
      - redis
    networks:
      - texas-net

networks:
  texas-net:
    driver: bridge